spring:
  datasource:
    url: jdbc:h2:mem:pricedb;DB_CLOSE_ON_EXIT=TRUE;DB_CLOSE_DELAY=-1
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

# Logging para ver más detalles de lo que ocurre
logging:
  level:
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG